### ISSUE TITLE
Android Studio 4.0  Gradle plugin 4.0.0 BUILD FAILED 

### ISSUE THREAD

**Issue by dakun666** [Tencent/VasDolly#102]
Could not get unknown property 'apkVariantData' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl

**Comment by Tinker-S** [comment]
https://my.oschina.net/redhouse/blog/4723720

**Comment by zhzephi** [comment]
使用修改后的插件包替换即可。下载地址：
链接：https://pan.baidu.com/s/12bdEv8GeALG6g_7pGdgqZQ
提取码：9b74

找到自己gradle缓存地址，（菜单-File-Settings-Build,Execution,Deployment-Gradle）下面，General settings，Gradle user home
我的在.gradle\caches\modules-2\files-2.1\com.leon.channel\plugin\2.0.3下，找到对应jar包本地地址，替换掉原来的即可。

**Comment by Tinker-S** [comment]
> 使用修改后的插件包替换即可。下载地址：
> 链接：https://pan.baidu.com/s/12bdEv8GeALG6g_7pGdgqZQ
> 提取码：9b74
> 
> 找到自己gradle缓存地址，（菜单-File-Settings-Build,Execution,Deployment-Gradle）下面，General settings，Gradle user home
> 我的在.gradle\caches\modules-2\files-2.1\com.leon.channel\plugin\2.0.3下，找到对应jar包本地地址，替换掉原来的即可。

恩，这样最简单了，不过这样只能针对本机环境生效，很多工程都是集成了jenkins等，这样就不太行了

**Comment by dakun666** [comment]
发布到自己的远程maven jenkins就可以用了吧

**Comment by Tinker-S** [comment]
> 发布到自己的远程maven jenkins就可以用了吧

可以呀，不过个人认为还是集成在代码里面方便，一个commit就搞定，将来官方更新了，把这个commit revert了更新下版本号就完事。

**Comment by yanyongshan** [comment]
升级到com.tencent.vasdolly:plugin:3.0.0
