### ISSUE TITLE
Android Studio从3.6.3升级到4.0.0后，channelRelease打包失败

### ISSUE THREAD

**Issue by tianyingzhong** [Tencent/VasDolly#104]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:channelRelease'.
> Could not get unknown property 'apkVariantData' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by tianyingzhong** [comment]
Gradle 版本是 6.1.1

**Comment by zhiqiang3927** [comment]
me too

**Comment by wxcican** [comment]
me too

**Comment by SamJonson** [comment]
me too

**Comment by ImmortalBird** [comment]
还没修复吗？

**Comment by nic562** [comment]
一样。就是说变量 apkVariantData 的问题。请问能否给修复一下

**Comment by zhzephi** [comment]
同样问题，期待修复

**Comment by Tinker-S** [comment]
https://my.oschina.net/redhouse/blog/4723720

**Comment by zhzephi** [comment]
使用修改后的插件包替换即可。下载地址：
链接：https://pan.baidu.com/s/12bdEv8GeALG6g_7pGdgqZQ
提取码：9b74

找到自己gradle缓存地址，（菜单-File-Settings-Build,Execution,Deployment-Gradle）下面，General settings，Gradle user home
我的在.gradle\caches\modules-2\files-2.1\com.leon.channel\plugin\2.0.3下，找到对应jar包本地地址，替换掉原来的即可。

**Comment by ConerK** [comment]
> https://my.oschina.net/redhouse/blog/4723720

新版本还是有这个问题呀

**Comment by Tinker-S** [comment]
> > https://my.oschina.net/redhouse/blog/4723720
> 
> 新版本还是有这个问题呀

没有新版本呀兄弟，官方一直没有更新版本。

**Comment by yanyongshan** [comment]
升级到com.tencent.vasdolly:plugin:3.0.0且要求com.android.tools.build版本大于4.2.0
