### ISSUE TITLE
rebuildChannel不支持apkNameFormat？

### ISSUE THREAD

**Issue by WhoIsAA** [Tencent/VasDolly#109]
我准备用360加固后的基础包打渠道包，但不支持apkNameFormat，那要如何修改渠道包的命名？

**Comment by yanyongshan** [comment]
支持，rebuildChannel时命名规则为：替换baseDebugApk/baseReleaseApk中设置的文件名中的‘base’这个字符，因此你可以先命名好你的baseApk即可，如baseReleaseApk为new File(project.projectDir, "baseApk/vasdolly_base-release.apk"),生成的文件名为：vasdolly_${channelName}-release.apk

**Comment by qyzhaojinxi** [comment]
相当于只是在前边加了个渠道，最好还是能支持apkNameFormat
