### ISSUE TITLE
gradle 4.0.2  报错

### ISSUE THREAD

**Issue by githubwxq** [Tencent/VasDolly#111]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:channelAaqianfanyidongRelease'.
> Could not get unknown property 'apkVariantData' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

* Try:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 40s

**Comment by yanyongshan** [comment]
升级到com.tencent.vasdolly:plugin:3.0.0

**Comment by yanyongshan** [comment]
同时要求com.android.tools.build:gradle大于等于4.2.0版本

**Comment by yanyongshan** [comment]
同时要求com.android.tools.build:gradle大于等于4.2.0版本
