### ISSUE TITLE
gralde 命令行指定 versionCode versionName 

### ISSUE THREAD

**Issue by buyiyun** [Tencent/VasDolly#113]
使用这个命令行「gradle channelDebug(channelRelease) -Pchannels=yingyongbao,gamecenter」的时候  怎么指定 version code 和 version name

**Comment by yanyongshan** [comment]
在app的build.gradle中添加配置，如：
channel{
    //指定渠道文件
    channelFile = file("/Users/leon/Downloads/testChannel.txt")
     //多渠道包的输出目录，默认为new File(project.buildDir,"channel")
    baseOutputDir = new File(project.buildDir,"xxx")
    //多渠道包的命名规则，默认为：${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}-${buildTime}
    apkNameFormat ='${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}'
    //快速模式：生成渠道包时不进行校验（速度可以提升10倍以上，默认为false）
    fastMode = false
    //buildTime的时间格式，默认格式：yyyyMMdd-HHmmss
    buildTimeDateFormat = 'yyyyMMdd-HH:mm:ss'
    //低内存模式（仅针对V2签名，默认为false）：只把签名块、中央目录和EOCD读取到内存，不把最大头的内容块读取到内存，在手机上合成APK时，可以使用该模式
    lowMemory = false
}
指定apkNameFormat的模板即可实现文件名变更，version code 和 version name，是当前应用的版本号
