### ISSUE TITLE
命令行添加渠道信息报not have precise channel package mode错误

### ISSUE THREAD

**Issue by wjh177** [Tencent/VasDolly#114]
命令行添加渠道信息报not have precise channel package mode错误。
apk地址是https://g66.gdl.netease.com/mrzh_release_netease_180.apk
是网易的明日之后

**Comment by wjh177** [comment]
这是具体的错误信息

`not have apk signature block
Exception in thread "main" java.lang.IllegalStateException: not have precise channel package mode
	at com.leon.channel.command.Util.writeChannel(Util.java:110)
	at com.leon.channel.command.Main.main(Main.java:175)`

**Comment by yanyongshan** [comment]
无法获取Apk的签名类型，检查签名算法是V1和V2,如在build.gradle中配置：
signingConfigs {
        release {
            ...
            v1SigningEnabled true
            v2SigningEnabled false
        }

        debug {
            ...
            v1SigningEnabled true
            v2SigningEnabled false
        }
    }
