### ISSUE TITLE
华为应用市场上传多渠道apk后，apk的渠道号就为null了，有解决方法吗

### ISSUE THREAD

**Issue by liyanfang** [Tencent/VasDolly#115]
java -jar VasDolly.jar get -c /Users/Downloads/base.apk
try to read channel info from apk : /Users/Downloads/base.apk
find V2 signature block Id : 1896449818
getByteBufferValueById , destApk /Users/Downloads/base.apk IdValueMap = {1896449818=java.nio.HeapByteBuffer[pos=0 lim=1343 cap=1343]}
getByteValueById , id = -2012129793 , value = null
APK : /Users/Downloads/base.apk not have channel info from Zip Comment

Channel: null

**Comment by FredLiu111** [comment]
朋友解决了吗

**Comment by yanyongshan** [comment]
确定这个上传的apk,与你从华为应用市场上下载的apk是同一个吗？

**Comment by warry19940712** [comment]
我也遇到这个问题了，特意从华为后台把Apk下载下来，安装到手机上是没问题的，就是从商店直接安装的，获取不到渠道号。

**Comment by sjdlfajdlfe** [comment]
华为把渠道号好像抹掉了。，也是刚发现

**Comment by warry19940712** [comment]
已和华为应用市场证实，已加入应用签名计划的应用，上传市场后会被二次签名。所以原渠道号会被抹掉。

**Comment by yanyongshan** [comment]
你可以使用V2签名打包，华为可能就不会删除渠道信息
