### ISSUE TITLE
VasDolly 如何添加额外信息，不同的渠道对应了不同参数？

### ISSUE THREAD

**Issue by yefangqingchen** [Tencent/VasDolly#116]
VasDolly 如何添加额外信息，不同的渠道对应了不同参数？

**Comment by yanyongshan** [comment]
渠道即代表额外信息，如渠道名qq，VasDolly会将‘qq’这个额外信息打入安装包中，并提供com.tencent.vasdolly:helper的工具在apk内部获取额外的信息，因此你可以随意定义渠道信息，然后再到app内解析字符串即可
