### ISSUE TITLE
使用命令行打包如何区分打包成功还是失败？

### ISSUE THREAD

**Issue by shenbingkai** [Tencent/VasDolly#117]
自动化打渠道包流程，在不看控制台日志的情况下，如何区分打包成功或失败？

**Comment by yanyongshan** [comment]
使用命令行时，可以获取指定APK的渠道信息，检查渠道信息
java -jar VasDolly.jar get -c /home/user/test.apk

https://github.com/Tencent/VasDolly/blob/master/command/README.md
