### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by Newwaygo** [Tencent/VasDolly#118]
过时了， 能更新下吗？

compile 不让用了。。。。

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':common')
}

**Comment by yanyongshan** [comment]
com.tencent.vasdolly:plugin:3.0.0
升级到3.0.0版本，支持AGP4.2.0以上
