### ISSUE TITLE
Unity 出的apk应该怎么通过代码获取channel信息呢？

### ISSUE THREAD

**Issue by 573271137** [Tencent/VasDolly#119]
我希望用VasDolly来出渠道包，之前的渠道信息是通过读取AndroidManifest.xml来获取，C#怎么调用helper类库中的ChannelReaderUtil呢？

**Comment by 573271137** [comment]
我好像知道了 可以用unity调用VasDolly的方法

**Comment by AaronChenJH** [comment]
怎么获取呢
