### ISSUE TITLE
channelDebug 和channelRelease 报错 无法用

### ISSUE THREAD

**Issue by cfba1715** [Tencent/VasDolly#124]
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':module_app:channelDebug' (type 'ApkChannelPackageTask').
  - In plugin 'com.tencent.vasdolly' type 'com.tencent.vasdolly.plugin.task.ApkChannelPackageTask' property 'outputDir' specifies directory '/codes/****/*****/****/*****/****/channel' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the directory exists before the task is called.
      2. Make sure that the task which produces the directory is declared as an input.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
11:38:48 上午: Task execution finished 'channelDebug'.

**Comment by yanyongshan** [comment]
主要是生成渠道后用于保存的channel文件夹不存在，可以在build/目录下新建channel文件夹，或者自定义输出目录，如：
channel{
    //多渠道包的输出目录，默认为new File(project.buildDir,"channel")
    baseOutputDir = new File(project.buildDir,"channels")
}

**Comment by yanyongshan** [comment]
V3.0.2已经修复

**Comment by totim19i78** [comment]
yanyongshan ***@***.***> ezt írta (időpont: 2021. nov. 25.,
Cs 10:38):
