### ISSUE TITLE
求助！编译失败

### ISSUE THREAD

**Issue by dongzhaosheng73** [Tencent/VasDolly#125]
> Task :kkacc:reBuildChannel FAILED
get channels from `channelFile`,channels:[qq, xiaomi, huawei, yijia]
Task reBuildChannel , channelList : [qq, xiaomi, huawei, yijia]
generateChannelApk baseApk:D:\android_git\kk_android\kkacc\build\outputs\apk\release\kkacc_release.apk,outputDir:D:\android_git\kk_android\kkacc\build\rebuildChannels

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kkacc:reBuildChannel'.
> java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
1 actionable task: 1 executed

**Comment by yanyongshan** [comment]
当前使用的不是Java11吧？

**Comment by yanyongshan** [comment]
升级到V3.0.3可以解决，已经在Java8环境重新编译
