### ISSUE TITLE
使用-Pchannels参数的问题

### ISSUE THREAD

**Issue by enzowyf** [Tencent/VasDolly#130]
使用`-Pchannels`指定渠道的时候，遇到报错

<img width="506" alt="企业微信截图_dd327d2c-9316-463a-977b-6e6abe01fb4e" src="https://user-images.githubusercontent.com/34463867/155733261-b300b4ed-1e7c-4ebe-9b90-ce8846cf9e42.png">

看了下源码`VasDollyPlugin.kt`中的函数`getChannelList`有bug，

<img width="934" alt="企业微信截图_9dac9e5e-e539-4cb0-ad71-35257af4d42a" src="https://user-images.githubusercontent.com/34463867/155732855-e276f20b-0d22-49b4-a464-2a3a73970568.png">

 
从`-Pchannels`取出来的值被装进了`channelInfoList`，而不是最后的返回值`channelList`，导致`-Pchannels`失效。

从log可以看到`channelList`是空的
<img width="527" alt="企业微信截图_e9b4d478-28a8-4b18-8d6d-de8d2645cec0" src="https://user-images.githubusercontent.com/34463867/155733282-a87b3a38-9a65-4f22-80c2-a60eebd69149.png">

**Comment by jigongdajiang** [comment]
没有。。。解决吗，最近

**Comment by lh1241698502** [comment]
> 使用`-Pchannels`指定渠道的时候，遇到报错
> 
> <img alt="企业微信截图_dd327d2c-9316-463a-977b-6e6abe01fb4e" width="506" src="https://user-images.githubusercontent.com/34463867/155733261-b300b4ed-1e7c-4ebe-9b90-ce8846cf9e42.png">
> 
> 看了下源码`VasDollyPlugin.kt`中的函数`getChannelList`有bug，
> 
> <img alt="企业微信截图_9dac9e5e-e539-4cb0-ad71-35257af4d42a" width="934" src="https://user-images.githubusercontent.com/34463867/155732855-e276f20b-0d22-49b4-a464-2a3a73970568.png">
> 
> 从`-Pchannels`取出来的值被装进了`channelInfoList`，而不是最后的返回值`channelList`，导致`-Pchannels`失效。
> 
> 从log可以看到`channelList`是空的 <img alt="企业微信截图_e9b4d478-28a8-4b18-8d6d-de8d2645cec0" width="527" src="https://user-images.githubusercontent.com/34463867/155733282-a87b3a38-9a65-4f22-80c2-a60eebd69149.png">

我也遇到了，啥时候能修复呢

**Comment by azhon** [comment]
还没解决吗？

**Comment by kennir** [comment]
这个问题还是存在

**Comment by kane313** [comment]
这个问题。。。太低级了吧？还没改掉。。。。

**Comment by yanyongshan** [comment]
主干代码中 已经解决了
