### ISSUE TITLE
打出来的渠道包没有签名

### ISSUE THREAD

**Issue by grins2193285007** [Tencent/VasDolly#131]
插件版号本和库版本号：3.0.4
gradle:4.2.2
gradle-6.7.1-bin.zip
compileSdkVersion 31
buildToolsVersion "30.0.3"
minSdkVersion 24
targetSdkVersion 30
打出来的多渠道包没有签名，不知道为什么？也不知道是不是compileSdkVersion的问题，以前使用都是正常的，后来根据已有的基础包生成多渠道包就可以了。

**Comment by yanyongshan** [comment]
渠道包打包，不会修改签名信息，你需要先检查是否已经签名，渠道修改是基于Base包打的，因此需要检查Base包是否签名
