### ISSUE TITLE
是不是 VasDolly v3.0.4，只支持 gradle 7.0.2 以上版本？

### ISSUE THREAD

**Issue by jeffreyxuworld** [Tencent/VasDolly#138]
我的项目环境如下：
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.3"
        classpath 'com.tencent.vasdolly:plugin:3.0.4'
    }
distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-all.zip

编译项目会报这个错：
Unable to load class 'com.android.build.api.extension.AndroidComponentsExtension'.
This is an unexpected error. Please file a bug containing the idea.log file.

----------------------------------------------------
将项目环境更改为：
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.3'
        classpath 'com.tencent.vasdolly:plugin:3.0.4'
    }
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip

即可成功编译，并且按教程配置，可以打出对应的渠道包。

**Comment by yanyongshan** [comment]
V3.0.4版本要求Android Gradle Plugin 4.2.0及以上版本
