### ISSUE TITLE
 UE5出的apk应该怎么通过代码获取channel信息呢？

### ISSUE THREAD

**Issue by AaronChenJH** [Tencent/VasDolly#142]

**Comment by AaronChenJH** [comment]
有实现的案例吗

**Comment by yanyongshan** [comment]
暂时没有直接提供UE5的访问，仅提供了插件包com.tencent.vasdolly:helper，你需要适当封装一下，调用此插件的接口

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1409736/212016946-b0abbaaf-ef3d-4f18-91b1-65dc08c28687.png">
