### ISSUE TITLE
channelRelease打包，会将渠道文件中#后面注释的内容一起打到渠道里

### ISSUE THREAD

**Issue by sixgodIT** [Tencent/VasDolly#146]
gradle 版本：com.android.tools.build:gradle:7.0.3
vasdolly 版本：com.tencent.vasdolly:plugin:3.0.4
channel.txt 文件内容：
> 101_01_01_000 #官网版本
101_01_01_002 #360手机助手

channelRelease打包，会将渠道文件中注释的内容一起打到渠道里。读取的渠道信息会带着 “#”，而使用 vasdolly.jar 命令行打包就不会出现该问题。
![image](https://user-images.githubusercontent.com/5539093/203481920-f1bdd901-1025-4022-a038-6e5a58f70933.png)

**Comment by yanyongshan** [comment]
channel.txt 不支持添加注释
