### ISSUE TITLE
关于多渠道加固

### ISSUE THREAD

**Issue by canhuah** [Tencent/VasDolly#27]
以前用的Umeng多渠道,一般打包一个包并且签名,在乐固里配置签名,配置多渠道, 比较简单(只需打包 签名 加固一个包)

那么用这个的话打包出很多渠道再挨个去加固吗

**Comment by ltlovezh** [comment]
只要打一个包，加固，签名。然后通过reBuildChannel模式生成多个渠道包，也是只要加固一个包。

**Comment by gmfbilu** [comment]
为什么我reBuildChannel后什么都没有生成啊

**Comment by ltlovezh** [comment]
请仔细检查日志提示，一般是参数配置错误，还是不行，可以加我QQ：1031747903
