### ISSUE TITLE
如何和友盟的渠道一起使用？

### ISSUE THREAD

**Issue by dotw** [Tencent/VasDolly#3]
渠道定义在什么地方了？如何与友盟的渠道集成？

**Comment by ltlovezh** [comment]
按照接入文档，生成渠道包后。
首先通过ChannelReaderUtil.getChannel(getApplicationContext())获取渠道信息，然后再通过友盟的API把渠道设置进去就行了哈。

**Comment by yzjjdcf** [comment]
请问如何和移动MTA统计  同时接入，怎么集成？ @ltlovezh

**Comment by ltlovezh** [comment]
是一样的（与友盟类似），我们也在使用MTA+VasDolly

**Comment by ltlovezh** [comment]
是一样的（与友盟类似），我们也在使用MTA+VasDolly

**Comment by yzjjdcf** [comment]
嗯，再MTA文档最末尾找到了。。尴尬。谢谢
