### ISSUE TITLE
渠道value 是否和walle一样容易被修改

### ISSUE THREAD

**Issue by caoshihong123456789** [Tencent/VasDolly#32]
我现在用的是walle 打的渠道包； 但是渠道包很容易就被修改成另一个渠道；而且已经上线的应用，下载下来渠道也变成了另一个渠道的值； 我想问 vasdolly 的机制和walle 一模一样吗；打出来的包会不会也这么容易就被修改了渠道value

**Comment by ltlovezh** [comment]
不好意思，目前因为添加渠道信息后不需要重新签名，所以不管是V1还是V2签名，都存在被篡改的风险。
目前有一种短期解决方案：自己用私钥对渠道信息加密，既：添加的是加密后的渠道信息。（目前小米这么做）。

针对这种容易被篡改的问题，近期我们会出一个部分签名的方案，彻底解决这类问题，尽请期待！

**Comment by ltlovezh** [comment]
小米游戏中心，给游戏及其渠道信息的
