### ISSUE TITLE
如何生成基础包

### ISSUE THREAD

**Issue by kennir** [Tencent/VasDolly#33]
1.是否通过```grade assembleRelease```命令生成基础包？
2.是否可以配置为```grade channelRelease```同时也生成一个基础包出来？以备还可以用命令行打一些不在channels.txt里的渠道

谢谢

**Comment by ltlovezh** [comment]
现在就是可以的哈，gradle channelFlavorXRelease,FlavorX表示你通过官方ProductFlavor配置的渠道，如果没有官方ProductFlavor配置的渠道，那就是channelDebug和channelRelease
