### ISSUE TITLE
报错SigningConfig is null , please check it

### ISSUE THREAD

**Issue by jtq1036012350** [Tencent/VasDolly#37]
* What went wrong:
Execution failed for task ':app:channelRelease'.
> SigningConfig is null , please check it
apply plugin: 'com.android.application'
apply plugin: 'channel'
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.marsjiang.myapplicationtest"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            storeFile file("")
            storePassword ""
            keyAlias ""
            keyPassword ""
            v1SigningEnabled true
            v2SigningEnabled false
        }
        debug {
            storeFile file("")
            storePassword ""
            keyAlias ""
            keyPassword ""
            v1SigningEnabled true
            v2SigningEnabled false
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    channel{
        //指定渠道文件
        channelFile = file("../channel.txt")
        //多渠道包的输出目录，默认为new File(project.buildDir,"channel")
        baseOutputDir = new File(project.buildDir,"channel")
        //多渠道包的命名规则，默认为：${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}
        apkNameFormat ='${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}'
        //快速模式：生成渠道包时不进行校验（速度可以提升10倍以上）
        isFastMode = true
    }
    rebuildChannel {
        baseDebugApk = new File(project.projectDir, "baseApk/v1-base-debug.apk")
        baseReleaseApk = new File(project.projectDir, "baseApk/v2-base-debug.apk")
        //isFastMode = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    api 'com.leon.channel:helper:1.1.7'
}

**Comment by jtq1036012350** [comment]
apply plugin: 'com.android.application'
apply plugin: 'channel'
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.marsjiang.myapplicationtest"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            storeFile file("")
            storePassword ""
            keyAlias ""
            keyPassword ""
            v1SigningEnabled true
            v2SigningEnabled false
        }
        debug {
            storeFile file("")
            storePassword ""
            keyAlias ""
            keyPassword ""
            v1SigningEnabled true
            v2SigningEnabled false
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    channel{
        //指定渠道文件
        channelFile = file("../channel.txt")
        //多渠道包的输出目录，默认为new File(project.buildDir,"channel")
        baseOutputDir = new File(project.buildDir,"channel")
        //多渠道包的命名规则，默认为：${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}
        apkNameFormat ='${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}'
        //快速模式：生成渠道包时不进行校验（速度可以提升10倍以上）
        isFastMode = true
    }
    rebuildChannel {
        baseDebugApk = new File(project.projectDir, "baseApk/v1-base-debug.apk")
        baseReleaseApk = new File(project.projectDir, "baseApk/v2-base-debug.apk")
        //isFastMode = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    api 'com.leon.channel:helper:1.1.7'
}

**Comment by LomoLin** [comment]
所以怎么解决的？
