### ISSUE TITLE
请问最近gradle升级到的4.x以上支持么

### ISSUE THREAD

**Issue by zengcanxiang** [Tencent/VasDolly#38]
如题所述

**Comment by ltlovezh** [comment]
应该支持的，已经支持Android Gradle Plugin3.0了

**Comment by zengcanxiang** [comment]
@ltlovezh  你说的Android gradle plugin 3.0是指`android.tools.build:gradle`么,还是指`gradle-3.x-all`?

**Comment by ltlovezh** [comment]
这个：android.tools.build:gradle，你可以先试下，理论上没问题，有问题我们再解决
