### ISSUE TITLE
增量更新是否会受影响呢

### ISSUE THREAD

**Issue by hc1991** [Tencent/VasDolly#39]
用bspatch 做增量更新是否会受影响呢，生成差分包是使用的不带渠道信息的原始包。在合成的时候是否会有问题呢？

**Comment by ltlovezh** [comment]
理论上会受影响，毕竟你使用Base包生成patch，但是合成的时候是带有渠道信息的，这两个包（Base包和带渠道信息的包）的MD5是不一样的。
不过你可以试下，如果有影响，那么所有添加渠道的方案应该都不行，因为每个渠道包在渠道信息这块都是有差异的，还是那句话：不同渠道包的MD5不一样。

**Comment by hc1991** [comment]
我试了，写comment增量合成不受影响，能够正常合成。但是如果是IDValue这种方式，合成的APK无法安装。我这边的解决方法是在合成的时候，将baseApk写入的渠道信息删除，再进行合成，但是删除APK的中添加的IDValue，手机上进行读写的时候内存消耗很大，删除IDValue这里有好建议吗？

**Comment by ltlovezh** [comment]
嗯，我当时全部读入内存，主要是为了快速拷贝（打渠道包一般都是在PC上），确实没有考虑到在手机上操作的场景。
只要操作签名块的话，理论上是没有必要把全部信息读入到内存的，只要读取签名块及后面的数据就可以了，而这部分内存占用其实是比较小的。
这块你也可以尝试修改一下，或者近期我来修改下，提供一种可选的低内存模式。
