### ISSUE TITLE
如何配置channel文件

### ISSUE THREAD

**Issue by zengcanxiang** [Tencent/VasDolly#40]
我看项目的配置，channel文件是每行一个渠道，我现在是有一个渠道名，有一个渠道Code，如何让这个配置在channel文件中？

使我在打包的时候，通过`flavorName`拿到我配置的渠道名，`String channel = ChannelReaderUtil.getChannel(getApplicationContext());`能拿到我其他的渠道信息

**Comment by zengcanxiang** [comment]
现在是在channel文件中将两个渠道信息用下划线连接起来，渠道apk的名字的format`${versionName}(${versionCode})_'+releaseTime()+'_${flavorName}_${buildType}`是这么配置的。

但是，有一点不完美的就是，就无法在打出的apk文件的名字去掉渠道code。无法执行方法，也没有办法获取渠道channel变量

**Comment by zengcanxiang** [comment]
而且一般都需要时间这个字段，能不能加上时间这个字段呢？

**Comment by ltlovezh** [comment]
时间的问题，马上就会加上。
你前面描述的问题，我没有理解什么意思？麻烦加Q沟通：1031747903

**Comment by zengcanxiang** [comment]
@ltlovezh 就是类似美团多渠道的，可以携带除了简单的渠道名之外的其他信息。

**Comment by ltlovezh** [comment]
目前暂时不支持，争取下个版本支持，谢谢反馈！
