### ISSUE TITLE
打包完成未释放资源

### ISSUE THREAD

**Issue by LetFree** [Tencent/VasDolly#43]
1.1.7版本
打包完成后，生成的文件或文件夹没有释放，导致资源无法移动或复制

**Comment by ltlovezh** [comment]
V2.0.0已修复，谢谢反馈

**Comment by LetFree** [comment]
V2.0.0已修复，但原始的签名包APK（app\build\outputs\apk里面的）资源未释放

**Comment by ltlovezh** [comment]
sorry,确实是我代码问题，紧急发布了V2.0.1版本，麻烦试一下
