### ISSUE TITLE
如何统计多渠道的下载量

### ISSUE THREAD

**Issue by smm113522** [Tencent/VasDolly#49]
那个后台统计应该可以看到不同渠道下载量吧？

**Comment by ltlovezh** [comment]
这个需要你们自己统计哈，根据渠道作为标识

**Comment by smm113522** [comment]
根据渠道作为标识？不明白怎么用？和上次到不同的应用市场，从里面看下载量也可以。但是和这个渠道打包就没有关系了吧？不知道怎么才能作为标示了？

**Comment by chenyusheng** [comment]
> 根据渠道作为标识？不明白怎么用？和上次到不同的应用市场，从里面看下载量也可以。但是和这个渠道打包就没有关系了吧？不知道怎么才能作为标示了？

自己接入友盟之类的统计工具就可以了
