### ISSUE TITLE
关于设置多个基准包的建议

### ISSUE THREAD

**Issue by qiangxi** [Tencent/VasDolly#52]
case如下：
- 部分渠道的apk有定制需求，这部分是采用gradle脚本实现（只有包的构建，没有加入渠道信息）
- 一个普通包
- 然后有部分包需要使用360加固

经过以上3步之后，会发现，有一个普通包，有多个定制包，有多个加固包，然后我要使用VasDolly构建多渠道，但是VasDolly貌似只能设置一个基础包，不能满足我的需求，请问有什么好的办法解决这个问题吗？

**Comment by ltlovezh** [comment]
目前确实是只支持设置一个debug和一个release的基础包，我考虑下这块的优化，感谢！
