### ISSUE TITLE
使用VasDolly生成的渠道包的渠道名是什么？

### ISSUE THREAD

**Issue by chenyusheng** [Tencent/VasDolly#54]
现在有个需求就是我用VasDolly生成的release版本提交给运营人员
但是运营人员随时还需要根据自己运营的需求对release包重新做一些临时的渠道包
目前他们用的360加固助手提供的渠道打包服务
但是多渠道配置的 统计平台并没有VasDolly的选项，就算选了InstallChannel 也没用，渠道打包出来的应用包还是没有渠道的
所以问题就是，渠道名应该填什么？
![image](https://user-images.githubusercontent.com/11496107/45149865-21666100-b1fd-11e8-8a7c-9165dbc759a2.png)

**Comment by ltlovezh** [comment]
Hi，目前要需通过VasDolly的API读取出渠道名，然后设置到APP里面去。也提供了脚本来获取某个apk的渠道名。

**Comment by chenyusheng** [comment]
我已经想到其他办法解决了
