### ISSUE TITLE
如何修改AndroidManifest.xml的${GRADLE_CHANNEL_VALUE}

### ISSUE THREAD

**Issue by bingxuebage** [Tencent/VasDolly#55]
如题，我现在有渠道信息写在AndroidManifest.xml中，引用的是GRADLE_CHANNEL_VALUE
我该如何通过channel配置将chanel中对应的渠道信息写入${GRADLE_CHANNEL_VALUE}

**Comment by saki1010** [comment]
同问

**Comment by ltlovezh** [comment]
这里要换一种思路，不需要在AndroidManifest.xml中添加GRADLE_CHANNEL_VALUE，而是通过VasDolly的API获取到渠道后，再通过友盟等的API把渠道设置进去。

**Comment by iBotasky** [comment]
@ltlovezh 这个思路具体要怎么实现呢，在网上搜了一下貌似找不到这种动态设置AndroidManifest的方案。

**Comment by fly7632785** [comment]
@iBotasky 一般的三方sdk，都有代码接口设置channel,
ChannelReaderUtil.getChannel(getApplicationContext()); 就可以获取channel，然后你再用代码设置进去就好了。

**Comment by gaoleicoding** [comment]
如友盟，可在代码中设置channel，UMUtils.setChannel(Context var0, String var1)
