### ISSUE TITLE
Generated v2 signature is not page aligned.

### ISSUE THREAD

**Issue by plecesne** [Tencent/VasDolly#59]
The APK signature is not page aligned (i.e. 4K alignment), and is rejected by apksig verifier.

See this change in apksig which added requirement in the page-alignement of the v2 signing block: 
https://android.googlesource.com/platform/tools/apksig/+/39a28bd4ba894920d0e5602526c2622cbe7b4f83%5E%21/#F0

**Comment by MichaelArchangel** [comment]
problem solved? @ltlovezh

**Comment by ltlovezh** [comment]
请使用V2.0.2及以上版本
