### ISSUE TITLE
rebuildChannel 能执行成功 channelRelease 提示 Task 'channelRelease' not found in root project

### ISSUE THREAD

**Issue by kanxue2002** [Tencent/VasDolly#61]
RT

**Comment by AlixChiong** [comment]
app 命名格式：apkNameFormat ='${appName}_${buildType}_${flavorName}_'+'#'+'${versionCode}_'+'v'+'${versionName}_${buildTime}'
buildTime的时间格式，默认格式：yyyyMMdd-HHmmss
打出来的包每个渠道会有两个重复的，不知道啥情况

**Comment by ltlovezh** [comment]
channelRelease的全称是channelFlavorXXDebug或者channelFlavorXXRelease，你一定是配置了ProductFlavor
