### ISSUE TITLE
白屏、设置渠道号问题

### ISSUE THREAD

**Issue by wangchunlei000** [Tencent/VasDolly#64]
集成了这种渠道包方式后，有几个问题想请教一下。
1.开发阶段使用AS打包后默认，是获取不到渠道号的，怎么能在开发阶段将渠道编号设置进去？
2.打包后首次安装启动，会有很长时间的白屏时间，请问这个怎么优化？
3.有没有可以将渠道号直接设置到AndroidManifest.xml中的UMENG_CHANNEL变量中去？

**Comment by ltlovezh** [comment]
1. 可以设置AS执行的Task，改成channelDebug或者channelRelease就行了。
2.白屏这个问题？你确定跟渠道有关系吗？你在启动的时候读取渠道了吗
3.目前没有，你可以读取到渠道信息后，通过相应的API设置进去
