### ISSUE TITLE
加固后使用build-tool/28.0.3/apksinger签名后重新生成渠道包在anroid9上安装失败

### ISSUE THREAD

**Issue by godisnoone** [Tencent/VasDolly#65]
加固后使用build-tool/28.0.3/apksinger签名后重新生成渠道包在anroid9上安装失败，报错信息如下：
adb: failed to install /Users/one/Android/app/build/rebuildChannel/release/app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl411273963.tmp/base.apk using APK Signature Scheme v3: Size of APK Signing Block is not a multiple of 4096: 4112]

**Comment by mayqlzu** [comment]
我也遇到了，求解！

**Comment by mayqlzu** [comment]
我目前估计是，使用apksigner的时候，默认使用了V1+V2+V3方案，而VasDolly还未支持V3方案；

**Comment by mayqlzu** [comment]
我发现用build-tools/27.0.3/apksigner签名出来再添加渠道的包，能在9.0正常安装，所以至少和apksigner版本有关；

**Comment by yxyaxng** [comment]
我也遇到了，有什么好的解决办法吗 @tencent-adm

**Comment by mayqlzu** [comment]
用更低版本的签名工具，例如 build-tools/27.0.3/apksigner；


yxyaxng <notifications@github.com> 于2019年1月4日周五 上午9:52写道：

**Comment by ltlovezh** [comment]
请使用V2.0.2版本
