### ISSUE TITLE
How to replace productFlavors.all

### ISSUE THREAD

**Issue by fly7632785** [Tencent/VasDolly#73]
Hello, I used multi flavor to take the place of multi channel originally.
But I use VasDolly，it means I can just use default flavor.
But I want to make BAIDU_CHANNEL_VALUE be flavor's channel.
How to replace it ? Please help. Thank you in advance.
```
  flavorDimensions "default"
    productFlavors {
//        other {}
//        cssj {}
//        csds {}
//        kuan {}
        productFlavors.all {
            flavor -> flavor.manifestPlaceholders = [BAIDU_CHANNEL_VALUE: name]
        }
    }
```

**Comment by fly7632785** [comment]
关于这个问题，我现在的解决版本是，设置各个不同的渠道的话，第三方的sdk直接在代码设置，而不使用占位。

现在有一个新的问题想要咨询一下，有没有什么办法，把channel的渠道 对应到 buildconfig的flavor里面去？

**Comment by fangasvsass** [comment]
找到其他更好的解决方法了吗
