### ISSUE TITLE
使用VasDolly进行多渠道打包的时候如何进行应用图标更换

### ISSUE THREAD

**Issue by choi006** [Tencent/VasDolly#75]
不少应用市场有图标要求，在使用VasDolly进行多渠道打包的时候如何进行应用图标更换

**Comment by chenyusheng** [comment]
> 不少应用市场有图标要求，在使用VasDolly进行多渠道打包的时候如何进行应用图标更换
配置一下productFlavors

**Comment by ltlovezh** [comment]
如果每个市场需要使用不同的图标，那么意味着每个APK都需要重新编译打包，那么VasDolly就不是很适合这个场景了，可以通过官方的productFlavors来实现多渠道打包。
