### ISSUE TITLE
使用kotlin开发的项目，报 compileReleaseKotlin 错误

### ISSUE THREAD

**Issue by maoai-xianyu** [Tencent/VasDolly#80]
> Task :parent:compileReleaseKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':parent:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by jerry0864** [comment]
你是怎么确定这个错误是打包工具产生的？
