### ISSUE TITLE
部分机型读取渠道失败

### ISSUE THREAD

**Issue by jerry0864** [Tencent/VasDolly#93]
有部分机型读取渠道失败，没有返回渠道信息，读取的api为ChannelReaderUtil.getChannel（context）：

失败机型：
MI NOTE LTE
ONEPLUS A5000
ONEPLUS A6000
ONEPLUS A5010

没有捕获到有异常日志；

**Comment by ltlovezh** [comment]
收到，我找对应机型试一下

**Comment by jerry0864** [comment]
最近观察了下，发现有些新机型出现。前几位：
RMX1901
vivo X20Plus A
Pixel 2
JSN-AL00a
MI 6

和机型应该没有太大关系。

你可以把ChannelReaderUtil.getChannel（context）返回为空的结果上报日志，
采样量大的情况下，可以重现。
出现获取渠道为空的情况占比还是非常少的。
所以，正常测试不太可能会碰得到。

**Comment by jerry0864** [comment]
> 收到，我找对应机型试一下

大佬 后续有关注过这个问题不，你们产品监控中没发现这个问题吗？
