### ISSUE TITLE
如何在签名块中添加自定义的附加信息呢？

### ISSUE THREAD

**Issue by bunny-pu** [Tencent/VasDolly#96]
如题

**Comment by yefangqingchen** [comment]
找到解决办法了吗，我也需要添加附加信息，不同的渠道对应了不同的参数

**Comment by yanyongshan** [comment]
打不同的渠道即可，如原渠道qq，改为多个渠道如：qq-arg1,qq-arg2,qq-arg3,然后应用类使用com.tencent.vasdolly:helper读取，然后解析出arg1,arg2,arg3
