### ISSUE TITLE
INFO: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'. It will be removed at the end of 2019.

### ISSUE THREAD

**Issue by zangpuu** [Tencent/VasDolly#97]
是不是有些过时的方法呢
INFO: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

**Comment by zangpuu** [comment]
![image](https://user-images.githubusercontent.com/5113982/71437900-80235700-272e-11ea-8c18-008fc99c2976.png)

**Comment by sfy666666** [comment]
找不到这个过时方法 我该怎么解决

**Comment by BoBoMEe** [comment]
com.leon.plugin.ApkChannelPackagePlugin$_apply_closure2$_closure5$_closure6.doCall(ApkChannelPackagePlugin.groovy:75) 这个方法

**Comment by yanyongshan** [comment]
升级到3.0.0
