### ISSUE TITLE
无法使用，gradle channelRelease，直接报错

### ISSUE THREAD

**Issue by PiPiCaptain** [Tencent/VasDolly#98]
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.

WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.

**Comment by yanyongshan** [comment]
升级到VasDolly 3.0.0,同时要求AGP4.2.0以上
